### PR TITLE
Add gitpod file

### PR DESCRIPTION
**Pull request by cartermp**

### CODE REVIEW

**Comment by dsyme** [comment]
TIL about gitpod :)

**Comment by cartermp** [comment]
still WIP :)

**Comment by dsyme** [comment]
"dotnet rool restore" ??

What is rool

**Comment by cartermp** [comment]
A typo! But it doesn't matter, I think this workspace-dotnet thing isn't quite working and I'll need a different docker file to pull in the .NET 5 image.

**Comment by cartermp** [comment]
Feel free to ignore this PR for a while, I'm playing with it on and off. As with any unix-based tool there's a bunch of different ways to do stuff and it's a little difficult to see if something is me screwing something up or if something is missing from gitpod

**Comment by dsyme** [comment]
> Feel free to ignore this PR for a while, I'm playing with it on and off. As with any unix-based tool there's a bunch of different ways to do stuff and it's a little difficult to see if something is me screwing something up or if something is missing from gitpod

But I'm enjoying the entertainment! :-)

**Comment by cartermp** [comment]
Monster!

**Comment by dsyme** [comment]
>Monster!

Always!

**Comment by cartermp** [comment]
Got it working!
image

**Pull request merged**
